 apiVersion: v1
 kind: Service
 metadata:
   name: micro-http
   namespace: default
   labels:
     micro: runtime
     name: http
     version: latest
 spec:
   ports:
   - name: http
     port: 8080
     targetPort: 8080
   selector:
     name: micro-http
     micro: runtime
     version: latest
