apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-proxy-latest
  labels:
    micro: runtime
    name: proxy
    version: latest
  annotations:
    name: "proxy"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-proxy
      micro: runtime
      version: latest
  template:
    metadata:
      labels:
        name: micro-proxy
        micro: runtime
        version: latest
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9000"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - micro-proxy
                    - key: micro
                      operator: In
                      values:
                        - runtime
                topologyKey: "kubernetes.io/hostname"
      
      
      containers:
      - name: micro
        env:
        - name: MICRO_PROXY
          value: "micro-network.default.svc.cluster.local:8443"
        - name: MICRO_SERVICE_NAME
          value: "proxy"
        - name: MICRO_AUTH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_public_key
        - name: MICRO_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_private_key
        - name: MICRO_PROFILE
          value: "client"
        - name: MICRO_REGISTRY_TLS_CA
          value: "/certs/registry/ca.crt"
        - name: MICRO_REGISTRY_TLS_CERT
          value: "/certs/registry/cert.pem"
        - name: MICRO_REGISTRY_TLS_KEY
          value: "/certs/registry/key.pem"
        - name: MICRO_LOG_LEVEL
          value: "trace"
        - name: MICRO_PROXY_ADDRESS
          value: ":443"
        args:
        - service
        - proxy
        image: mcbeam-hub.tencentcloudcr.com/wolfplus/mcbeam:mcbeam-v3-20210928-483fb4aece9e21601ed901a49ffa79d73aae4b17
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: proxy-port
        readinessProbe:
          tcpSocket:
            port: proxy-port
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - name: etcd-client-certs
            mountPath: "/certs/registry"
            readOnly: true
      volumes:
        - name: etcd-client-certs
          secret:
            secretName: etcd-client-certs