apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-websocket-latest
  labels:
    micro: runtime
    name: websocket
    version: latest
  annotations:
    name: "websocket"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-websocket
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-websocket
        micro: runtime
        version: latest
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9000"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - micro-api
                    - key: micro
                      operator: In
                      values:
                        - runtime
                topologyKey: "kubernetes.io/hostname"
      
      
      containers:
      - name: micro
        env:
        - name: MICRO_API_RESOLVER
          value: subdomain
        - name: MICRO_AUTH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_public_key
        - name: MICRO_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_private_key
        - name: MICRO_PROFILE
          value: "client"
        - name: MICRO_SERVICE_NAME
          value: websocket
        - name: MICRO_REGISTRY_TLS_CA
          value: "/certs/registry/ca.crt"
        - name: MICRO_REGISTRY_TLS_CERT
          value: "/certs/registry/cert.pem"
        - name: MICRO_REGISTRY_TLS_KEY
          value: "/certs/registry/key.pem"
        - name: MICRO_PROXY
          value: "micro-network.default.svc.cluster.local:8443"
        - name: MICRO_LOG_LEVEL
          value: "debug"
        - name: MICRO_TRACING_REPORTER_ADDRESS
          value: "jaeger-tracing-agent.monitoring.svc.cluster.local:6831"
        args:
        - service
        - websocket
        image: mcbeam-hub.tencentcloudcr.com/wolfplus/mcbeam-dev:mcbeam-dev-20211019-42c69bd2be0f04ffbc29f5fdc4834c5fe779fa0c
        imagePullPolicy: Always
        ports:
        - containerPort: 3251
          name: websocket-port
        readinessProbe:
          tcpSocket:
            port: websocket-port
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - name: etcd-client-certs
            mountPath: "/certs/registry"
            readOnly: true
      volumes:
        - name: etcd-client-certs
          secret:
            secretName: etcd-client-certs