apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grpc-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
#  tls:
#    - hosts:
#        - "*.mcbeam.cc"
#      secretName: proxy-tls
  rules:
    - host: "proxy.mcbeam.cc"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: micro-proxy
              servicePort: 8081
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
#  tls:
#  - hosts:
#      - "*.mcbeam.cc"
#    secretName: api-tls
  rules:
  - host: "api.mcbeam.cc"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: micro-api
          servicePort: 8080
  - host: "*.mcbeam.cc"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: micro-api
            servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "*.mcbeam.cc"
      http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              serviceName: micro-http
              servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: websocket-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
      #配置websocket 需要的配置
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  rules:
  - host: "*.mcbeam.cc"
    http:
      paths:
        - path: /websocket
          pathType: Prefix
          backend:
            serviceName: micro-gate
            servicePort: 3250

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: config-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "apollo.mcbeam.cc"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: apollo-portal
              servicePort: 8070
    - host: "apollo-srv.mcbeam.cc"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: apollo-service-apollo-configservice
              servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
#  tls:
#    - hosts:
#        - "*.mcbeam.cc"
#      secretName: api-tls
  rules:
    - host: "grafana.mcbeam.cc"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: grafana
              servicePort: 80