version: '3'
services:
#  nats:
#    image: nats
#    ports:
#      - 4222:4222
  etcd:
    image: appcelerator/etcd
    hostname: etcd
    ports:
      - 2379:2379
  redis:
    hostname: redis
    image: redis:alpine